# Generated by Django 2.1.7 on 2019-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_button',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
