# Generated by Django 2.1.7 on 2019-03-11 13:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_content',
            field=wagtail.core.fields.StreamField([('text_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='Add text', required=True))]))], blank=True),
        ),
    ]
