# Generated by Django 2.1.7 on 2019-03-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0004_homepage_intro_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
