# Generated by Django 2.1.7 on 2019-03-11 15:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_intro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='service',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('service', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('description', wagtail.core.blocks.CharBlock(required=True))])))]))], blank=True),
        ),
    ]
