# Generated by Django 2.1.7 on 2019-03-12 10:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0006_homepage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='project1_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project1_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project2_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project2_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('service', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('description', wagtail.core.blocks.CharBlock(required=True)), ('blob', wagtail.documents.blocks.DocumentChooserBlock(required=True))])))]))], blank=True),
        ),
    ]
