# Generated by Django 2.1.7 on 2019-03-14 16:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='job',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.StructBlock([('job', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('category', wagtail.core.blocks.CharBlock(max_length=50, required=True))])))]))], blank=True),
        ),
    ]
